[package]
name = "sofer-core"
version = "0.1.0"
authors = ["Jorge BS <jorge.jbs@protonmail.com>"]
license = "GPL-3.0"

[profile.release]
lto = true

[dependencies]
rlua = "^0.8"
hlist-macro = "^0.1.0"
uuid = { version = "0.4", features = ["serde", "v4"] }
clap = "~2.19.0"
xml-rs = "0.6"
